[package]
name = "wsol"
version = "1.0.0"
edition = "2021"
authors = ["tropicbliss <tropicbliss@protonmail.com>"]
license = "MIT"
description = "A simple and fast Wordle word finder"

[profile.release]
debug = true

[dependencies]
clap = { version = "3", features = ["derive"] }
