[package]
name = "wsol"
version = "1.6.11"
edition = "2021"
authors = ["tropicbliss <tropicbliss@protonmail.com>"]
license = "MIT"
description = "A simple and fast Wordle word finder"

[dependencies]
clap = { version = "3.0.14", features = ["derive"] }